export const dataEnglish = [
  {
    id: 1,
    title: "Courage the cowardly Dog Funky Black T-shirt",
    rating: 4.5,
    price: 999,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["featured", "cartoon"],
    showTags: ["featured", "cartoon"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 2,
    title: "All you need is a new dress quote Black T-shirt",
    rating: 4.5,
    price: 499,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Women's Clothing",
    tags: ["featured", "quotes"],
    showTags: ["featured", "quote"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 3,
    title: "All in one - DBZ, Naruto, One punch man, One piece T-shirt",
    rating: 4.5,
    price: 1299,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["featured", "anime"],
    showTags: ["featured", "anime"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 4,
    title: "Itachi Uchiha Anime White T-shirt",
    rating: 4.5,
    price: 1299,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["featured", "anime"],
    showTags: ["featured", "anime"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 5,

    title: "SQL Query Black T-shirt",
    rating: 4.5,
    price: 1199,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["latest", "developer"],
    showTags: ["latest", "developer"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 6,

    title: "Engineer Girl T-shirt",
    rating: 4.5,
    price: 1199,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Women's Clothing",
    tags: ["latest", "engineering"],
    showTags: ["latest", "engineering"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 7,
    title: "Being Sleepy Girl pink T-shirt",
    rating: 4.5,
    price: 1199,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Women's Clothing",
    tags: ["latest", "quote"],
    showTags: ["latest", "quote"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 8,
    title: "Bad Boy Black T-shirt",
    rating: 4.5,
    price: 1199,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["latest", "quote"],
    showTags: ["latest", "quote"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 9,
    title: "Alcohol is Solution Black T-shirt",
    rating: 4.5,
    price: 1199,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Special Edition",
    tags: ["latest", "quote"],
    showTags: ["latest", "quote"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 10,
    title: "Friends- I'll be there for you T-shirt",
    rating: 3.9,
    price: 899,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Special Edition",
    tags: ["latest", "unisex", "quote"],
    showTags: ["latest", "unisex", "quote"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 11,
    title: "Chai is the secret of my energy T-shirt",
    rating: 3.9,
    price: 899,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Special Edition",
    tags: ["grid", "unisex", "quote"],
    showTags: ["grid", "unisex", "quote"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 12,
    title: "Courage the cowardly Dog classic pale green T-shirt",
    rating: 4.5,
    price: 1299,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["grid", "cartoon"],
    showTags: ["grid", "cartoon"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 13,
    title: "A developer and tester can never be FRIEND T-shirt",
    rating: 4.5,
    price: 1299,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["grid", "quote"],
    showTags: ["grid", "quote"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 14,
    title: "All you need is a new dress quote Black T-shirt",
    rating: 4.5,
    price: 499,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Women's Clothing",
    tags: ["grid", "quotes"],
    showTags: ["grid", "quotes"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 15,

    title: "Itachi Uchiha Anime White T-shirt",
    rating: 4.5,
    price: 1299,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["grid", "anime"],
    showTags: ["grid", "developer"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 16,

    title: "Being Sleepy Girl pink T-shirt",
    rating: 4.5,
    price: 1199,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Women's Clothing",
    tags: ["grid", "quote"],
    showTags: ["latest", "developer"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 17,

    title: "GANG STAA Beige T-shirt",
    rating: 4.5,
    price: 1199,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["grid", "funky"],
    showTags: ["technology", "developer"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 18,
    title: "Galti Badi Galti Engineering T-shirt",
    rating: 4.5,
    price: 1199,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["grid", "funky", "quote"],
    showTags: ["humor", "developer"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 19,
    title: "Courage the cowardly Dog Funky Black T-shirt",
    rating: 4.5,
    price: 999,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["grid", "cartoon"],
    showTags: ["developer", "coding"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 20,
    title: "Bad Boy Black T-shirt",
    rating: 4.5,
    price: 1199,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["grid", "quote"],
    showTags: ["developer", "fullstack"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 21,
    title: "Do I look like hangover white Tshirt",
    rating: 4.5,
    price: 1199,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["grid", "quote"],
    showTags: ["grid", "quote"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 22,
    title: "SQL Query Black T-shirt",
    rating: 4.5,
    price: 1199,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["grid", "developer"],
    showTags: ["grid", "developer"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 23,

    title: "Courage the cowardly Dog Funky Black T-shirt",
    rating: 4.5,
    price: 999,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["list", "cartoon"],
    showTags: ["list", "cartoon"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 24,

    title: "Itachi Uchiha Anime White T-shirt",
    rating: 4.5,
    price: 1299,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["list", "anime"],
    showTags: ["list", "anime"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 25,
    title: "Courage the cowardly Dog classic pale green T-shirt",
    rating: 4.5,
    price: 1299,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["list", "cartoon"],
    showTags: ["list", "cartoon"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 26,

    title: "Engineer Girl T-shirt",
    rating: 4.5,
    price: 1199,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Women's Clothing",
    tags: ["list", "engineering"],
    showTags: ["list", "engineering"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 27,
    title: "GANG STAA Beige T-shirt",
    rating: 4.5,
    price: 1199,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["list", "funky"],
    showTags: ["list", "funky"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 28,
    title: "Bad Boy Black T-shirt",
    rating: 4.5,
    price: 1199,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["list", "quote"],
    showTags: ["list", "quote"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 29,
    title: "Do I look like hangover white Tshirt",
    rating: 4.5,
    price: 1199,
    description:
      "Give your closet an instant upgrade by opting for the trendy cwc styled or your own Styled T-shirt. It features a distinctive graphic pattern and is designed in a black hue. This T-shirt is made from soft yet durable cotton material and features a crew and half sleeves.",
    category: "Men's Clothing",
    tags: ["list", "quote"],
    showTags: ["list", "quote"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
];

export const dataHindi = [
  {
    id: 1,
    title: "कायर कुत्ता फंकी काला टी-शर्ट",
    rating: 4.5,
    price: 999,
    description:
      "अपने अलमारी को तुरंत अपडेट करें और ट्रेंडी CWC स्टाइल या अपनी स्टाइल की टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम लेकिन मजबूत कॉटन सामग्री से बनी है और इसमें क्रू और आधी बांहें हैं।",
    category: "पुरुषों के कपड़े",
    tags: ["featured", "cartoon"],
    showTags: ["विशेष रुप से प्रदर्शित", "कार्टून"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 2,
    title: "तुम्हें बस एक नया ड्रेस चाहिए क्यूट ब्लैक टी-शर्ट",
    rating: 4.5,
    price: 499,
    description:
      "अपने अलमारी को तुरंत अपडेट करें और ट्रेंडी CWC स्टाइल या अपनी स्टाइल की टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम लेकिन मजबूत कॉटन सामग्री से बनी है और इसमें क्रू और आधी बांहें हैं।",
    category: "महिलाओं के कपड़े",
    tags: ["featured", "quotes"],
    showTags: ["विशेष रुप से प्रदर्शित", "उद्धरण"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 3,
    title: "सभी एक में - DBZ, नaruटो, वन पंच मैन, वन पीस टी-शर्ट",
    rating: 4.5,
    price: 1299,
    description:
      "अपने अलमारी को तुरंत अपडेट करें और ट्रेंडी CWC स्टाइल या अपनी स्टाइल की टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम लेकिन मजबूत कॉटन सामग्री से बनी है और इसमें क्रू और आधी बांहें हैं।",
    category: "पुरुषों के कपड़े",
    tags: ["featured", "anime"],
    showTags: ["विशेष रुप से प्रदर्शित", "एनीमे"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 4,
    title: "इटाची उचिहा एनीमे सफेद टी-शर्ट",
    rating: 4.5,
    price: 1299,
    description:
      "अपने अलमारी को तुरंत अपडेट करें और ट्रेंडी CWC स्टाइल या अपनी स्टाइल की टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम लेकिन मजबूत कॉटन सामग्री से बनी है और इसमें क्रू और आधी बांहें हैं।",
    category: "पुरुषों के कपड़े",
    tags: ["featured", "anime"],
    showTags: ["विशेष रुप से प्रदर्शित", "एनीमे"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 5,
    title: "SQL क्वेरी काला टी-शर्ट",
    rating: 4.5,
    price: 1199,
    description:
      "अपने अलमारी को तुरंत अपडेट करें और ट्रेंडी CWC स्टाइल या अपनी स्टाइल की टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम लेकिन मजबूत कॉटन सामग्री से बनी है और इसमें क्रू और आधी बांहें हैं।",
    category: "पुरुषों के कपड़े",
    tags: ["latest", "developer"],
    showTags: ["नवीनतम", "विकासकर्ता"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 6,
    title: "इंजीनियर गर्ल टी-शर्ट",
    rating: 4.5,
    price: 1199,
    description:
      "अपने अलमारी को तुरंत अपडेट करें और ट्रेंडी CWC स्टाइल या अपनी स्टाइल की टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम लेकिन मजबूत कॉटन सामग्री से बनी है और इसमें क्रू और आधी बांहें हैं।",
    category: "महिलाओं के कपड़े",
    tags: ["latest", "engineering"],
    showTags: ["नवीनतम", "इंजीनियरिंग"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 7,
    title: "बीइंग स्लीपी गर्ल गुलाबी टी-शर्ट",
    rating: 4.5,
    price: 1199,
    description:
      "अपने अलमारी को तुरंत अपडेट करें और ट्रेंडी CWC स्टाइल या अपनी स्टाइल की टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम लेकिन मजबूत कॉटन सामग्री से बनी है और इसमें क्रू और आधी बांहें हैं।",
    category: "महिलाओं के कपड़े",
    tags: ["latest", "quote"],
    showTags: ["नवीनतम", "उद्धरण"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 8,
    title: "बैड बॉय काला टी-शर्ट",
    rating: 4.5,
    price: 1199,
    description:
      "अपने अलमारी को तुरंत अपडेट करें और ट्रेंडी CWC स्टाइल या अपनी स्टाइल की टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम लेकिन मजबूत कॉटन सामग्री से बनी है और इसमें क्रू और आधी बांहें हैं।",
    category: "पुरुषों के कपड़े",
    tags: ["latest", "quote"],
    showTags: ["नवीनतम", "उद्धरण"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 9,
    title: "आल्कोहल ही हल है काला टी-शर्ट",
    rating: 4.5,
    price: 1199,
    description:
      "अपने अलमारी को तुरंत अपडेट करें और ट्रेंडी CWC स्टाइल या अपनी स्टाइल की टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम लेकिन मजबूत कॉटन सामग्री से बनी है और इसमें क्रू और आधी बांहें हैं।",
    category: "विशेष संस्करण",
    tags: ["latest", "quote"],
    showTags: ["नवीनतम", "उद्धरण"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 10,
    title: "फ्रेंड्स- मैं तुम्हारे लिए हमेशा रहूँगा टी-शर्ट",
    rating: 3.9,
    price: 899,
    description:
      "अपने अलमारी को तुरंत अपडेट करें और ट्रेंडी CWC स्टाइल या अपनी स्टाइल की टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम लेकिन मजबूत कॉटन सामग्री से बनी है और इसमें क्रू और आधी बांहें हैं।",
    category: "विशेष संस्करण",
    tags: ["latest", "unisex", "quote"],
    showTags: ["नवीनतम", "यूनिसेक्स", "उद्धरण"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 11,
    title: "चाय ही मेरी ऊर्जा का रहस्य है टी-शर्ट",
    rating: 3.9,
    price: 899,
    description:
      "अपने अलमारी को तुरंत अपडेट करें और ट्रेंडी CWC स्टाइल या अपनी स्टाइल की टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम लेकिन मजबूत कॉटन सामग्री से बनी है और इसमें क्रू और आधी बांहें हैं।",
    category: "विशेष संस्करण",
    tags: ["grid", "unisex", "quote"],
    showTags: ["ग्रिड", "यूनिसेक्स", "उद्धरण"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 12,
    title: "कायर कुत्ता क्लासिक हल्का हरा टी-शर्ट",
    rating: 4.5,
    price: 1299,
    description:
      "अपने अलमारी को तुरंत अपडेट करें और ट्रेंडी CWC स्टाइल या अपनी स्टाइल की टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम लेकिन मजबूत कॉटन सामग्री से बनी है और इसमें क्रू और आधी बांहें हैं।",
    category: "पुरुषों के कपड़े",
    tags: ["grid", "cartoon"],
    showTags: ["ग्रिड", "कार्टून"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 13,
    title: "डेवलपर और टेस्टर्स कभी FRIEND नहीं हो सकते टी-शर्ट",
    rating: 4.5,
    price: 1299,
    description:
      "अपने अलमारी को तुरंत अपडेट करें और ट्रेंडी CWC स्टाइल या अपनी स्टाइल की टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम लेकिन मजबूत कॉटन सामग्री से बनी है और इसमें क्रू और आधी बांहें हैं।",
    category: "पुरुषों के कपड़े",
    tags: ["grid", "quote"],
    showTags: ["ग्रिड", "उद्धरण"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 14,
    title: "तुम्हें बस एक नया ड्रेस चाहिए क्यूट ब्लैक टी-शर्ट",
    rating: 4.5,
    price: 499,
    description:
      "अपने अलमारी को तुरंत अपडेट करें और ट्रेंडी CWC स्टाइल या अपनी स्टाइल की टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम लेकिन मजबूत कॉटन सामग्री से बनी है और इसमें क्रू और आधी बांहें हैं।",
    category: "महिलाओं के कपड़े",
    tags: ["grid", "quotes"],
    showTags: ["ग्रिड", "उद्धरण"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 15,
    title: "हर जगह साइड से हैक का दबाव टी-शर्ट",
    rating: 4.5,
    price: 1299,
    description:
      "अपने अलमारी को तुरंत अपडेट करें और ट्रेंडी CWC स्टाइल या अपनी स्टाइल की टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम लेकिन मजबूत कॉटन सामग्री से बनी है और इसमें क्रू और आधी बांहें हैं।",
    category: "विशेष संस्करण",
    tags: ["grid", "developer"],
    showTags: ["ग्रिड", "विकासकर्ता"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 16,
    title: "मशीन लर्निंग नीड टी-शर्ट",
    rating: 4.7,
    price: 1099,
    description:
      "आपके कार्यक्षेत्र या कॉलेज के लिए आदर्श मशीन लर्निंग टी-शर्ट। इसकी सुंदरता में इसका डिज़ाइन और शांत संदेश है जो यह सुनिश्चित करता है कि आपकी पूरी टीम इसके साथ मेल खाती है। इसका विशेष डिजाइन इसे ध्यान आकर्षित करने वाला बनाता है।",
    category: "पुरुषों के कपड़े",
    tags: ["latest", "developer"],
    showTags: ["नवीनतम", "विकासकर्ता"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 17,
    title: "इनोवेटिव कोडर टी-शर्ट",
    rating: 4.8,
    price: 1299,
    description:
      "एक पेशेवर कोडर के लिए आदर्श टी-शर्ट, जो तकनीकी परिधान और प्रैक्टिकल डिज़ाइन दोनों को महत्व देता है। यह टी-शर्ट सॉफ्ट कॉटन से बनी है और इसे लंबे समय तक पहनने के लिए डिज़ाइन किया गया है। यह प्रौद्योगिकी के प्रेमियों के लिए उपयुक्त है।",
    category: "पुरुषों के कपड़े",
    tags: ["technology", "developer"],
    showTags: ["प्रौद्योगिकी", "विकासकर्ता"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 18,
    title: "प्रोग्रामर जॉक्स येलो टी-शर्ट",
    rating: 4.6,
    price: 999,
    description:
      "आपके प्रिय प्रोग्रामिंग जोक्स के साथ यह येलो टी-शर्ट निश्चित रूप से किसी भी डेवलपर के दिन को रोशन करेगी। यह हल्के कपड़े से बनी है और बहुत आरामदायक है।",
    category: "पुरुषों के कपड़े",
    tags: ["humor", "developer"],
    showTags: ["हास्य", "विकासकर्ता"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 19,
    title: "सी++ लवर्स ग्रे टी-शर्ट",
    rating: 4.7,
    price: 1099,
    description:
      "सी++ प्रेमियों के लिए आदर्श टी-शर्ट। इसका हल्का ग्रे रंग और सिंपल डिज़ाइन इसे किसी भी अवसर पर पहना जा सकता है। यह प्रोग्रामर की हर अलमारी का हिस्सा बन सकता है।",
    category: "पुरुषों के कपड़े",
    tags: ["developer", "coding"],
    showTags: ["विकासकर्ता", "कोडिंग"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 20,
    title: "फुल स्टैक डेवेलपर ग्रीन टी-शर्ट",
    rating: 4.8,
    price: 1199,
    description:
      "फुल स्टैक डेवलपर्स के लिए यह ग्रीन टी-शर्ट एक आदर्श विकल्प है। इसका साधारण और आकर्षक डिज़ाइन एक कोडर की विशेषज्ञता को दर्शाता है। यह टी-शर्ट आपको हर मंच पर फिट होने का अहसास दिलाएगी।",
    category: "पुरुषों के कपड़े",
    tags: ["developer", "fullstack"],
    showTags: ["विकासकर्ता", "फुलस्टैक"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 21,
    title: "क्या मैं हैंगओवर सफेद टी-शर्ट जैसा दिखता हूँ",
    rating: 4.5,
    price: 1199,
    description:
      "अपनी अलमारी को एक ताजगी देने के लिए ट्रेंडी CWC स्टाइल या अपनी खुद की स्टाइल वाली टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम और टिकाऊ कपास सामग्री से बनी है और इसमें क्रू और आधी बाँहें हैं।",
    category: "पुरुषों का वस्त्र",
    tags: ["grid", "quote"],
    showTags: ["ग्रिड", "उद्धरण"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 22,
    title: "SQL क्वेरी काले रंग की टी-शर्ट",
    rating: 4.5,
    price: 1199,
    description:
      "अपनी अलमारी को एक ताजगी देने के लिए ट्रेंडी CWC स्टाइल या अपनी खुद की स्टाइल वाली टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम और टिकाऊ कपास सामग्री से बनी है और इसमें क्रू और आधी बाँहें हैं।",
    category: "पुरुषों का वस्त्र",
    tags: ["grid", "developer"],
    showTags: ["ग्रिड", "विकासकर्ता"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 23,
    title: "करेज द काऊर्डली डॉग फंकी काले रंग की टी-शर्ट",
    rating: 4.5,
    price: 999,
    description:
      "अपनी अलमारी को एक ताजगी देने के लिए ट्रेंडी CWC स्टाइल या अपनी खुद की स्टाइल वाली टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम और टिकाऊ कपास सामग्री से बनी है और इसमें क्रू और आधी बाँहें हैं।",
    category: "पुरुषों का वस्त्र",
    tags: ["list", "cartoon"],
    showTags: ["सूची", "कार्टून"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 24,
    title: "इताची उचिहा एनीमे सफेद टी-शर्ट",
    rating: 4.5,
    price: 1299,
    description:
      "अपनी अलमारी को एक ताजगी देने के लिए ट्रेंडी CWC स्टाइल या अपनी खुद की स्टाइल वाली टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम और टिकाऊ कपास सामग्री से बनी है और इसमें क्रू और आधी बाँहें हैं।",
    category: "पुरुषों का वस्त्र",
    tags: ["list", "anime"],
    showTags: ["सूची", "एनीमे"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 25,
    title: "करेज द काऊर्डली डॉग क्लासिक हल्का हरा टी-शर्ट",
    rating: 4.5,
    price: 1299,
    description:
      "अपनी अलमारी को एक ताजगी देने के लिए ट्रेंडी CWC स्टाइल या अपनी खुद की स्टाइल वाली टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम और टिकाऊ कपास सामग्री से बनी है और इसमें क्रू और आधी बाँहें हैं।",
    category: "पुरुषों का वस्त्र",
    tags: ["list", "cartoon"],
    showTags: ["सूची", "कार्टून"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 26,
    title: "इंजीनियर गर्ल टी-शर्ट",
    rating: 4.5,
    price: 1199,
    description:
      "अपनी अलमारी को एक ताजगी देने के लिए ट्रेंडी CWC स्टाइल या अपनी खुद की स्टाइल वाली टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम और टिकाऊ कपास सामग्री से बनी है और इसमें क्रू और आधी बाँहें हैं।",
    category: "महिलाओं का वस्त्र",
    tags: ["list", "engineering"],
    showTags: ["सूची", "इंजीनियरिंग"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 27,
    title: "गैंग स्टा बेज रंग की टी-शर्ट",
    rating: 4.5,
    price: 1199,
    description:
      "अपनी अलमारी को एक ताजगी देने के लिए ट्रेंडी CWC स्टाइल या अपनी खुद की स्टाइल वाली टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम और टिकाऊ कपास सामग्री से बनी है और इसमें क्रू और आधी बाँहें हैं।",
    category: "पुरुषों का वस्त्र",
    tags: ["list", "funky"],
    showTags: ["सूची", "फंकी"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 28,
    title: "बैड बॉय काली टी-शर्ट",
    rating: 4.5,
    price: 1199,
    description:
      "अपनी अलमारी को एक ताजगी देने के लिए ट्रेंडी CWC स्टाइल या अपनी खुद की स्टाइल वाली टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम और टिकाऊ कपास सामग्री से बनी है और इसमें क्रू और आधी बाँहें हैं।",
    category: "पुरुषों का वस्त्र",
    tags: ["list", "quote"],
    showTags: ["सूची", "उद्धरण"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 29,
    title: "क्या मैं हैंगओवर सफेद टी-शर्ट जैसा दिखता हूँ",
    rating: 4.5,
    price: 1199,
    description:
      "अपनी अलमारी को एक ताजगी देने के लिए ट्रेंडी CWC स्टाइल या अपनी खुद की स्टाइल वाली टी-शर्ट चुनें। इसमें एक विशिष्ट ग्राफिक पैटर्न है और यह काले रंग में डिज़ाइन की गई है। यह टी-शर्ट मुलायम और टिकाऊ कपास सामग्री से बनी है और इसमें क्रू और आधी बाँहें हैं।",
    category: "पुरुषों का वस्त्र",
    tags: ["list", "quote"],
    showTags: ["सूची", "उद्धरण"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
];

export const dataArabic = [
  {
    id: 1,
    title: "قميص أسود فاخر كورتج ذو التصميم الكرتوني",
    rating: 4.5,
    price: 999,
    description:
      "امنح خزانتك ترقية فورية باختيار تي شيرت عصري بتصميم CWC أو تصميمك الخاص. يتميز بنمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ودائم ويتميز بياقة دائرية وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["featured", "cartoon"],
    showTags: ["مميز", "كرتون"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 2,
    title: "كل ما تحتاجه هو فستان جديد - قميص أسود",
    rating: 4.5,
    price: 499,
    description:
      "امنح خزانتك ترقية فورية باختيار تي شيرت عصري بتصميم CWC أو تصميمك الخاص. يتميز بنمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ودائم ويتميز بياقة دائرية وأكمام نصفية.",
    category: "ملابس نسائية",
    tags: ["featured", "quotes"],
    showTags: ["مميز", "اقتباس"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 3,
    title: "كل شيء في واحد - قميص دي بي زد، ناروتو، ون بنش مان، ون بيس",
    rating: 4.5,
    price: 1299,
    description:
      "امنح خزانتك ترقية فورية باختيار تي شيرت عصري بتصميم CWC أو تصميمك الخاص. يتميز بنمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ودائم ويتميز بياقة دائرية وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["featured", "anime"],
    showTags: ["مميز", "أنمي"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 4,
    title: "قميص أبيض إيتاتشي أوتشيها أنمي",
    rating: 4.5,
    price: 1299,
    description:
      "امنح خزانتك ترقية فورية باختيار تي شيرت عصري بتصميم CWC أو تصميمك الخاص. يتميز بنمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ودائم ويتميز بياقة دائرية وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["featured", "anime"],
    showTags: ["مميز", "أنمي"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 5,
    title: "قميص أسود استعلام SQL",
    rating: 4.5,
    price: 1199,
    description:
      "امنح خزانتك ترقية فورية باختيار تي شيرت عصري بتصميم CWC أو تصميمك الخاص. يتميز بنمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ودائم ويتميز بياقة دائرية وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["latest", "developer"],
    showTags: ["أحدث", "مطور"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 6,
    title: "قميص فتاة مهندس",
    rating: 4.5,
    price: 1199,
    description:
      "امنح خزانتك ترقية فورية باختيار تي شيرت عصري بتصميم CWC أو تصميمك الخاص. يتميز بنمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ودائم ويتميز بياقة دائرية وأكمام نصفية.",
    category: "ملابس نسائية",
    tags: ["latest", "engineering"],
    showTags: ["أحدث", "هندسة"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 7,
    title: "قميص فتاة ناعسة وردي",
    rating: 4.5,
    price: 1199,
    description:
      "امنح خزانتك ترقية فورية باختيار تي شيرت عصري بتصميم CWC أو تصميمك الخاص. يتميز بنمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ودائم ويتميز بياقة دائرية وأكمام نصفية.",
    category: "ملابس نسائية",
    tags: ["latest", "quote"],
    showTags: ["أحدث", "اقتباس"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 8,
    title: "قميص فتى سيء أسود",
    rating: 4.5,
    price: 1199,
    description:
      "امنح خزانتك ترقية فورية باختيار تي شيرت عصري بتصميم CWC أو تصميمك الخاص. يتميز بنمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ودائم ويتميز بياقة دائرية وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["latest", "quote"],
    showTags: ["أحدث", "اقتباس"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 9,
    title: "قميص أسود الكحول هو الحل",
    rating: 4.5,
    price: 1199,
    description:
      "امنح خزانتك ترقية فورية باختيار تي شيرت عصري بتصميم CWC أو تصميمك الخاص. يتميز بنمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ودائم ويتميز بياقة دائرية وأكمام نصفية.",
    category: "إصدار خاص",
    tags: ["latest", "quote"],
    showTags: ["أحدث", "اقتباس"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 10,
    title: "أصدقاء- سأكون هناك من أجلك قميص",
    rating: 3.9,
    price: 899,
    description:
      "امنح خزانتك ترقية فورية باختيار تي شيرت عصري بتصميم CWC أو تصميمك الخاص. يتميز بنمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ودائم ويتميز بياقة دائرية وأكمام نصفية.",
    category: "إصدار خاص",
    tags: ["latest", "unisex", "quote"],
    showTags: ["أحدث", "يونيكس", "اقتباس"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 11,
    title: "تي شيرت الشاي هو سر طاقتي",
    rating: 3.9,
    price: 899,
    description:
      "امنحي خزانة ملابسك ترقية فورية عن طريق اختيار تي شيرت مميز بتصميم cwc أو تصميمك الخاص. يحتوي على نمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ولكنه قوي، ويتميز بأكمام قصيرة وأكمام نصفية.",
    category: "إصدار خاص",
    tags: ["grid", "unisex", "quote"],
    showTags: ["شبكة", "يونيكس", "اقتباس"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 12,
    title: "تي شيرت كوراچ الكلب الجبان الأخضر الفاتح الكلاسيكي",
    rating: 4.5,
    price: 1299,
    description:
      "امنحي خزانة ملابسك ترقية فورية عن طريق اختيار تي شيرت مميز بتصميم cwc أو تصميمك الخاص. يحتوي على نمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ولكنه قوي، ويتميز بأكمام قصيرة وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["grid", "cartoon"],
    showTags: ["شبكة", "كرتون"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 13,
    title: "تي شيرت 'المطور والمختبر لا يمكن أن يكونا أصدقاء'",
    rating: 4.5,
    price: 1299,
    description:
      "امنحي خزانة ملابسك ترقية فورية عن طريق اختيار تي شيرت مميز بتصميم cwc أو تصميمك الخاص. يحتوي على نمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ولكنه قوي، ويتميز بأكمام قصيرة وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["grid", "quote"],
    showTags: ["شبكة", "اقتباس"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 14,
    title: "تي شيرت 'كل ما تحتاجه هو فستان جديد' الأسود مع اقتباس",
    rating: 4.5,
    price: 499,
    description:
      "امنحي خزانة ملابسك ترقية فورية عن طريق اختيار تي شيرت مميز بتصميم cwc أو تصميمك الخاص. يحتوي على نمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ولكنه قوي، ويتميز بأكمام قصيرة وأكمام نصفية.",
    category: "ملابس نسائية",
    tags: ["grid", "quotes"],
    showTags: ["شبكة", "اقتباس"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 15,
    title: "تي شيرت إيتاتشي أوتشيها الأبيض من الأنمي",
    rating: 4.5,
    price: 1299,
    description:
      "امنحي خزانة ملابسك ترقية فورية عن طريق اختيار تي شيرت مميز بتصميم cwc أو تصميمك الخاص. يحتوي على نمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ولكنه قوي، ويتميز بأكمام قصيرة وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["grid", "developer"],
    showTags: ["شبكة", "مطور"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 16,
    title: "تي شيرت 'الفتاة النائمة' الوردي",
    rating: 4.5,
    price: 1199,
    description:
      "امنحي خزانة ملابسك ترقية فورية عن طريق اختيار تي شيرت مميز بتصميم cwc أو تصميمك الخاص. يحتوي على نمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ولكنه قوي، ويتميز بأكمام قصيرة وأكمام نصفية.",
    category: "ملابس نسائية",
    tags: ["latest", "developer"],
    showTags: ["أحدث", "مطور"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 17,
    title: "تي شيرت GANG STAA البيج",
    rating: 4.5,
    price: 1199,
    description:
      "امنحي خزانة ملابسك ترقية فورية عن طريق اختيار تي شيرت مميز بتصميم cwc أو تصميمك الخاص. يحتوي على نمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ولكنه قوي، ويتميز بأكمام قصيرة وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["technology", "developer"],
    showTags: ["تقنية", "مطور"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 18,
    title: "تي شيرت 'غلطتي الكبيرة' الهندسي",
    rating: 4.5,
    price: 1199,
    description:
      "امنحي خزانة ملابسك ترقية فورية عن طريق اختيار تي شيرت مميز بتصميم cwc أو تصميمك الخاص. يحتوي على نمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ولكنه قوي، ويتميز بأكمام قصيرة وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["humor", "developer"],
    showTags: ["فكاهي", "مطور"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 19,
    title: "تي شيرت كوراچ الكلب الجبان الأسود فانكي",
    rating: 4.5,
    price: 999,
    description:
      "امنحي خزانة ملابسك ترقية فورية عن طريق اختيار تي شيرت مميز بتصميم cwc أو تصميمك الخاص. يحتوي على نمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ولكنه قوي، ويتميز بأكمام قصيرة وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["developer", "coding"],
    showTags: ["مطور", "برمجة"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 20,
    title: "تي شيرت 'ولد سيء' الأسود",
    rating: 4.5,
    price: 1199,
    description:
      "امنحي خزانة ملابسك ترقية فورية عن طريق اختيار تي شيرت مميز بتصميم cwc أو تصميمك الخاص. يحتوي على نمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ولكنه قوي، ويتميز بأكمام قصيرة وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["developer", "fullstack"],
    showTags: ["مطور", "فولستاك"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 21,
    title: "هل أبدو كأني في حالة سكر؟ تي شيرت أبيض",
    rating: 4.5,
    price: 1199,
    description:
      "امنح خزانة ملابسك ترقية فورية عن طريق اختيار تي شيرت مميز بتصميم cwc أو تصميمك الخاص. يحتوي على نمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ولكنه قوي، ويتميز بأكمام قصيرة وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["grid", "quote"],
    showTags: ["شبكة", "اقتباس"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 22,
    title: "تي شيرت SQL Query الأسود",
    rating: 4.5,
    price: 1199,
    description:
      "امنح خزانة ملابسك ترقية فورية عن طريق اختيار تي شيرت مميز بتصميم cwc أو تصميمك الخاص. يحتوي على نمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ولكنه قوي، ويتميز بأكمام قصيرة وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["grid", "developer"],
    showTags: ["شبكة", "مطور"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 23,
    title: "تي شيرت كوراچ الكلب الجبان الأسود فانكي",
    rating: 4.5,
    price: 999,
    description:
      "امنح خزانة ملابسك ترقية فورية عن طريق اختيار تي شيرت مميز بتصميم cwc أو تصميمك الخاص. يحتوي على نمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ولكنه قوي، ويتميز بأكمام قصيرة وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["list", "cartoon"],
    showTags: ["قائمة", "كرتون"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 24,
    title: "تي شيرت إيتاتشي أوتشيها الأبيض من الأنمي",
    rating: 4.5,
    price: 1299,
    description:
      "امنح خزانة ملابسك ترقية فورية عن طريق اختيار تي شيرت مميز بتصميم cwc أو تصميمك الخاص. يحتوي على نمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ولكنه قوي، ويتميز بأكمام قصيرة وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["list", "anime"],
    showTags: ["قائمة", "أنمي"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 25,
    title: "تي شيرت كوراچ الكلب الجبان الأخضر الفاتح الكلاسيكي",
    rating: 4.5,
    price: 1299,
    description:
      "امنح خزانة ملابسك ترقية فورية عن طريق اختيار تي شيرت مميز بتصميم cwc أو تصميمك الخاص. يحتوي على نمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ولكنه قوي، ويتميز بأكمام قصيرة وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["list", "cartoon"],
    showTags: ["قائمة", "كرتون"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 26,
    title: "تي شيرت الفتاة المهندسة",
    rating: 4.5,
    price: 1199,
    description:
      "امنح خزانة ملابسك ترقية فورية عن طريق اختيار تي شيرت مميز بتصميم cwc أو تصميمك الخاص. يحتوي على نمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ولكنه قوي، ويتميز بأكمام قصيرة وأكمام نصفية.",
    category: "ملابس نسائية",
    tags: ["list", "engineering"],
    showTags: ["قائمة", "هندسة"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 27,
    title: "تي شيرت GANG STAA البيج",
    rating: 4.5,
    price: 1199,
    description:
      "امنح خزانة ملابسك ترقية فورية عن طريق اختيار تي شيرت مميز بتصميم cwc أو تصميمك الخاص. يحتوي على نمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ولكنه قوي، ويتميز بأكمام قصيرة وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["list", "funky"],
    showTags: ["قائمة", "فانكي"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 28,
    title: "تي شيرت ولد سيء الأسود",
    rating: 4.5,
    price: 1199,
    description:
      "امنح خزانة ملابسك ترقية فورية عن طريق اختيار تي شيرت مميز بتصميم cwc أو تصميمك الخاص. يحتوي على نمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ولكنه قوي، ويتميز بأكمام قصيرة وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["list", "quote"],
    showTags: ["قائمة", "اقتباس"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
  {
    id: 29,
    title: "هل أبدو كأني في حالة سكر؟ تي شيرت أبيض",
    rating: 4.5,
    price: 1199,
    description:
      "امنح خزانة ملابسك ترقية فورية عن طريق اختيار تي شيرت مميز بتصميم cwc أو تصميمك الخاص. يحتوي على نمط رسومي مميز ويأتي باللون الأسود. هذا التي شيرت مصنوع من قطن ناعم ولكنه قوي، ويتميز بأكمام قصيرة وأكمام نصفية.",
    category: "ملابس رجالية",
    tags: ["list", "quote"],
    showTags: ["قائمة", "اقتباس"],
    size: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
  },
];
